# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# pool:
#   vmImage: ubuntu-latest

pool: capacitor

steps:
- script: echo Hello, World!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: oc-setup@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-aro-cluster-connect'
    version: '4.10.46'


- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-aro-cluster-connect'
    version: '4.10'
    cmd: 'whoami --show-server'
# - task: oc-cmd@3
#   inputs:
#     connectionType: 'OpenShift Connection Service'
#     openshiftService: 'openshift-aro-cluster-connect'
#     cmd: 'new-project a-jims-project'
# - task: oc-setup@3
#   inputs:
#     connectionType: 'OpenShift Connection Service'
#     openshiftService: 'openshift-aro-cluster-connect'
#     version: 'https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-4.10/openshift-client-linux.tar.gz'
# - script: |
#     sleep 60
#     oc status
#     oc whoami --show-server
#     oc new-project a-jims-project

